# Generated by Django 4.1 on 2022-11-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_marriage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marriage',
            name='MarriageCertificate',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.CreateModel(
            name='childdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChildName', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('ParentsMarriageID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.marriage')),
            ],
        ),
    ]
