# Generated by Django 4.1 on 2022-11-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_marriage_marriagecertificate_childdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriage',
            name='Spousename',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
